name: CI for Backend

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Cambia a la versión que uses

      - name: Install dependencies for backend
        run: |
          # Instalar dependencias del backend principal
          cd backend
          pip install -r requirements.txt

      - name: Install dependencies for containers/backend
        run: |
          # Instalar dependencias de containers/backend
          cd containers/backend
          pip install -r requirements.txt

      - name: Install dependencies for modeloPlanos/server
        run: |
          # Instalar dependencias de modeloPlanos/server
          cd modeloPlanos/server
          pip install -r requirements.txt

      #- name: Run tests
      #  run: |
          # Ejecutar las pruebas unitarias
      #    cd backend  # O la carpeta principal donde estén las pruebas
      #    pytest  # O el comando que uses para ejecutar las pruebas
