name: CI for Backend

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js para el backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta la versión de Node.js según la que uses en el proyecto

      # Instalar dependencias de Node.js
      - name: Install Node.js dependencies
        run: |
          cd backend  # Cambia a la ruta donde están los archivos Node.js
          npm install  # Instala las dependencias de Node.js

      # Configurar Python (si aún necesitas esta parte)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Cambia la versión si es necesario

      # Instalar dependencias de Python para el backend
      #- name: Install dependencies for backend (Python)
      #  run: |
      #    cd backend  # Asegúrate de estar en la carpeta correcta
      #    pip install -r requirements.txt

      - name: Install dependencies for containers/backend (Python)
        run: |
          cd containers/backend
          pip install -r requirements.txt

      - name: Install dependencies for modeloPlanos/server (Python)
        run: |
          cd modeloPlanos/server
          pip install -r requirements.txt

      # Configurar variables de entorno
      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> $GITHUB_ENV
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
